fruit_client:
    resource: "@FruitBundle/Resources/config/routing/client.yml"
    prefix:   /client

rag_home:
    path:      /page
    defaults:  { _controller: FruitBundle:First:index }


fruit_homepage:
    path:     /BonnePoire
    defaults: { _controller: FruitBundle:Default:index }
