fruit_post:
    resource: "@FruitBundle/Controller/PostController.php"
    type:     annotation

fruit:
    resource: "@FruitBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
